name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Save current file list
        id: save_file_list
        run: |
          git ls-files > before_files.txt

      - name: Generate sitemap
        run: node utils/generate-sitemap.js

      - name: List affected files
        run: |
          git ls-files > after_files.txt
          git diff --name-only > affected_files.txt
          echo "Changed files:"
          cat affected_files.txt

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit sitemap
        run: |
          git add sitemap.xml
          git commit -m ":construction_worker: Update sitemap.xml" || true
          git pull --rebase
          git push origin main

      - name: Print affected files
        if: success()
        run: |
          echo "The following files were affected by the change:"
          cat affected_files.txt
